#########################
# START GOOGLE ANALYTICS
#########################

##REQUIRED##

#GoogleAnalyticsSTE:
  #main_code: 1234

#GoogleAnalyticsSTE:
  #site_name: 'bla'

##OPTIONAL##

#########################
# END GOOGLE ANALYTICS
#########################
