#########################
# START GOOGLE ANALYTICS
#########################

SiteTree:
  extensions:
    - GoogleAnalyticsSTE


#########################
# END GOOGLE ANALYTICS
#########################
